#importar imagen base de python
FROM python:3.12-slim

#crear en el contenedor Carpeta Trabajo
WORKDIR /app

#copiar los requerimientos 
COPY requirements.txt .

#instalamos las dependencias de FASTAPI
RUN pip install --no-cache-dir -r requirements.txt 

#copiar el codigo del servidor 
COPY ./app ./app

#exponer el puerto de trabajao
EXPOSE 5001

#comando a ejecutar para levanar el servidor 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]

# el punto (.) difce que pase el archivo exactamente igual al contenedor